(()=>{
const clone=x=>JSON.parse(JSON.stringify(x));
document.querySelector('.beta').textContent='CMS 3.3 · SCROLL FIX';
let website=clone(window.SHIZUKU_DATA), order=clone(window.SHIZUKU_ORDER_DATA), mode='website', activeWebsite='brand', activeOrder='brand';
const $=s=>document.querySelector(s), shell=$('#shell'), frame=$('#previewFrame'), websitePanels=$('#websitePanels'), orderPanels=$('#orderPanels');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fonts=['Gloock','DM Sans','Noto Serif JP','Playfair Display','Cormorant Garamond'];
const websiteSections=[['Brand & Logo','brand','home'],['Page Styles','styles','home'],['Hero','hero','home'],['Philosophy','philosophy','philosophy'],['Our Story','story','story'],['Our Tea','tea','tea'],['Why Us','why','why'],['Tea Library','library','library'],['Japan Matcha Atlas','atlas','library'],['Menu','menu','menu'],['From the Lab','updates','updates'],['Contact','contact','contact']];
const orderSections=[['Brand','brand','#menu'],['Products','products','#menu'],['Drink Options','options','#menu'],['Collection','collection','.hours'],['Promo','promo','#menu']];
function ensureStyleDefaults(root){const styles=root.sectionStyles||{};Object.values(styles).forEach(v=>{if(v.bodySizeDesktop==null)v.bodySizeDesktop=Number(v.bodySize??16);if(v.bodySizeMobile==null)v.bodySizeMobile=Number(v.bodySize??v.bodySizeDesktop??16);if(v.titleSizeDesktop==null)v.titleSizeDesktop=Number(v.titleSize??72);if(v.titleSizeMobile==null)v.titleSizeMobile=Number(v.titleSizeDesktop??48)});root.textStyles=root.textStyles||{};root.brand.navLabels=root.brand.navLabels||{story:'Our Story',tea:'Our Tea',why:'Why Us',library:'Tea Library',menu:'Menu',updates:'From the Lab',contact:'Contact',order:'Reserve your cup'};root.philosophy.image=root.philosophy.image||root.hero.image;if(root.philosophy.video==null)root.philosophy.video='assets/philosophy-matcha-pour.mp4';if(root.philosophy.videoShade==null)root.philosophy.videoShade=58;root.contact.collectionLabel??='Collection';root.contact.instagramLabel??='Instagram';root.contact.ordersLabel??='Orders';root.contact.orderText??='Reserve your cup ↗';root.contact.positions=root.contact.positions||{collection:'Left',instagram:'Centre',orders:'Right'};['tea.items','why.items','library.topics','library.cultivars','atlas.regions','menu','updates'].forEach(path=>{const current=get(root,path),fallback=get(window.SHIZUKU_DATA,path);if((!Array.isArray(current)||current.length===0)&&Array.isArray(fallback)&&fallback.length)set(root,path,clone(fallback))});}
ensureStyleDefaults(website);
function get(root,path){return path.split('.').reduce((o,k)=>o?.[k],root)}
function set(root,path,val){const ks=path.split('.');let o=root;ks.slice(0,-1).forEach(k=>{if(o[k]==null)o[k]={};o=o[k]});const last=ks.at(-1),old=o[last];if(typeof old==='number')o[last]=Number(val);else if(typeof old==='boolean')o[last]=val===true||val==='true';else o[last]=val}
function typography(path){const s=get(website,'textStyles.'+path)||{};return `<details class="type-control"><summary>Font & size for this text</summary><div class="row"><label class="field"><span>Font</span><select data-scope="website" data-path="textStyles.${path}.font"><option value="">Use section font</option>${fonts.map(o=>`<option ${o===s.font?'selected':''}>${esc(o)}</option>`).join('')}</select></label><label class="field"><span>Desktop size (px)</span><input data-scope="website" data-path="textStyles.${path}.desktop" type="number" min="6" max="300" value="${esc(s.desktop||'')}"></label></div><label class="field"><span>Mobile size (px)</span><input data-scope="website" data-path="textStyles.${path}.mobile" type="number" min="6" max="200" value="${esc(s.mobile||'')}"></label></details>`}
function field(label,path,value,type='text',opts=[],scope='website'){const editableType=scope==='website'&&(type==='text'||type==='textarea')&&!/(Url|URL|\.id$|\.status$)/i.test(path),extra=editableType?typography(path):'';if(type==='textarea')return `<div class="text-field-wrap"><label class="field"><span>${label}</span><textarea data-scope="${scope}" data-path="${path}">${esc(value)}</textarea></label>${extra}</div>`;if(type==='select')return `<label class="field"><span>${label}</span><select data-scope="${scope}" data-path="${path}">${opts.map(o=>`<option ${String(o)===String(value)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;if(type==='image')return imageField(label,path,value,scope);return `<div class="text-field-wrap"><label class="field"><span>${label}</span><input data-scope="${scope}" data-path="${path}" type="${type}" value="${esc(value)}"></label>${extra}</div>`}
function imageField(label,path,value,scope='website'){
 const inputId='img-'+scope+'-'+path.replace(/[^a-zA-Z0-9_-]/g,'-');
 const src=esc(value||'');
 if(scope==='order')return `<div class="field image-field simple-image-field"><span>${label}</span><input id="${inputId}" class="image-file-input" type="file" accept="image/*" data-order-image="${path}"><div class="image-crop simple-preview ${value?'':'is-empty'}"><img src="${src}" style="object-fit:cover"><em>No photo</em></div><div class="image-file-actions"><button type="button" class="ghost-btn" data-image-pick="#${inputId}">${value?'Replace Photo':'Choose Photo'}</button>${value?`<button type="button" class="ghost-btn danger-soft" data-image-remove-order="${path}">Remove Photo</button>`:''}</div></div>`;
 if(!/\.image$/.test(path))return `<div class="field image-field simple-image-field"><span>${label}</span><input id="${inputId}" class="image-file-input" type="file" accept="image/*" data-website-image="${path}"><div class="image-crop simple-preview ${value?'':'is-empty'}"><img src="${src}" style="object-fit:contain"><em>No photo</em></div><div class="image-file-actions"><button type="button" class="ghost-btn" data-image-pick="#${inputId}">${value?'Replace Photo':'Choose Photo'}</button>${value?`<button type="button" class="ghost-btn danger-soft" data-image-remove-website="${path}">Remove Photo</button>`:''}</div></div>`;
 const base=path.replace(/\.image$/,''),obj=get(website,base)||{},pd=obj.imagePositionDesktop||obj.imagePosition||{x:50,y:50},pm=obj.imagePositionMobile||obj.imagePosition||{x:50,y:50},sd=obj.imageScaleDesktop??obj.imageScale??1,sm=obj.imageScaleMobile??obj.imageScale??1;
 return `<div class="field image-field crop-image-field" data-image-field="${base}" data-image-device="desktop"><span>${label}</span><input id="${inputId}" class="image-file-input" type="file" accept="image/*" data-website-image="${path}"><div class="device-mini"><button type="button" class="active" data-img-device="desktop">Desktop</button><button type="button" data-img-device="mobile">Mobile</button></div><div class="image-crop ${value?'':'is-empty'}" data-image-editor="${base}"><img src="${src}" style="object-position:${pd.x}% ${pd.y}%;transform:scale(${sd});transform-origin:${pd.x}% ${pd.y}%"><em>No photo</em></div><div class="image-tools"><small>Drag photo to reposition</small><label>Zoom <input type="range" min="1" max="2.5" step="0.05" value="${sd}" data-image-scale="${base}" ${value?'':'disabled'}></label><button type="button" class="ghost-btn" data-image-reset="${base}" ${value?'':'disabled'}>Reset</button></div><div class="image-file-actions"><button type="button" class="ghost-btn" data-image-pick="#${inputId}">${value?'Replace Photo':'Choose Photo'}</button>${value?`<button type="button" class="ghost-btn danger-soft" data-image-remove-website="${path}">Remove Photo</button>`:''}</div><input type="hidden" data-pos-d="${base}" value="${pd.x},${pd.y},${sd}"><input type="hidden" data-pos-m="${base}" value="${pm.x},${pm.y},${sm}"></div>`
}
function videoField(label,path,value){const inputId='video-'+path.replace(/[^a-zA-Z0-9_-]/g,'-');return `<div class="field video-field"><span>${label}</span><input id="${inputId}" class="image-file-input" type="file" accept="video/mp4,video/quicktime" data-website-video="${path}"><div class="image-crop simple-preview ${value?'':'is-empty'}">${value?`<video src="${esc(value)}" muted loop autoplay playsinline style="width:100%;height:100%;object-fit:cover"></video>`:'<em>No video — the image will be used</em>'}</div><p class="editor-note">Recommended: muted MP4, 5–7 seconds, under 6MB.</p><div class="image-file-actions"><button type="button" class="ghost-btn" data-image-pick="#${inputId}">${value?'Replace Video':'Choose Video'}</button>${value?`<button type="button" class="ghost-btn danger-soft" data-video-remove="${path}">Remove Video</button>`:''}</div></div>`}
function posPad(label,path,v){v=v||{x:50,y:50};const marker=n=>(Number(n)+25)/1.5;return `<div class="field"><span>${label} <small>(drag beyond the page edge)</small></span><div class="position-pad position-pad-wide" data-position-pad="${path}"><b style="left:${marker(v.x)}%;top:${marker(v.y)}%"></b></div><div class="row position-values">${field('X %',path+'.x',v.x,'number')}${field('Y %',path+'.y',v.y,'number')}</div></div>`}
function actions(list,i){return `<div class="small-actions"><button type="button" class="drag-handle" draggable="true" data-drag-list="${list}" data-index="${i}" aria-label="drag"><i></i><i></i><i></i><i></i><i></i><i></i></button><button type="button" class="delete" data-delete="${list}" data-index="${i}">Delete</button></div>`}
function metaFields(prefix,obj,subtitle=true){return `${field('Eyebrow',prefix+'.eyebrow',obj.eyebrow||'')}${field('Title',prefix+'.title',obj.title||'','textarea')}${subtitle?field('Subtitle',prefix+'.subtitle',obj.subtitle||'','textarea'):''}${obj.body!==undefined?field('Body',prefix+'.body',obj.body,'textarea'):''}`}
function renderNav(){websiteNav.innerHTML=websiteSections.map(([t,id])=>`<button class="${activeWebsite===id?'active':''}" data-web-panel="${id}">${t}</button>`).join('');orderNav.innerHTML=orderSections.map(([t,id])=>`<button class="${activeOrder===id?'active':''}" data-order-panel="${id}">${t}</button>`).join('')}
function renderWebsitePanels(){const s=website.sectionStyles||{};websitePanels.innerHTML=`
<section class="panel ${activeWebsite==='brand'?'active':''}" data-panel="brand"><div class="group">${imageField('Logo','brand.logo',website.brand.logo)}<div class="row">${field('Logo colour','brand.logoColor',website.brand.logoColor,'color')}${field('Accent','brand.accent',website.brand.accent,'color')}</div><div class="row">${field('Desktop logo size','brand.logoDesktop',website.brand.logoDesktop,'number')}${field('Mobile logo size','brand.logoMobile',website.brand.logoMobile,'number')}</div><div class="row">${posPad('Desktop logo position','brand.logoDesktopPosition',website.brand.logoDesktopPosition)}${posPad('Mobile logo position','brand.logoMobilePosition',website.brand.logoMobilePosition)}</div><div class="item"><div class="item-head"><h3>Menu titles</h3></div><p class="editor-note">Each title can have its own font and size.</p>${Object.entries(website.brand.navLabels).map(([k,v])=>field(k==='order'?'Order button':k[0].toUpperCase()+k.slice(1),`brand.navLabels.${k}`,v)).join('')}</div>${field('Studio descriptor','brand.descriptor',website.brand.descriptor)}${field('Order URL','brand.orderUrl',website.brand.orderUrl)}${field('Instagram URL','brand.instagramUrl',website.brand.instagramUrl)}</div></section>
<section class="panel ${activeWebsite==='styles'?'active':''}" data-panel="styles"><div class="group">${Object.entries(s).map(([k,v])=>`<div class="item"><div class="item-head"><h3>${k[0].toUpperCase()+k.slice(1)}</h3></div><div class="row">${field('Paper colour',`sectionStyles.${k}.background`,v.background,'color')}${field('Title colour',`sectionStyles.${k}.titleColor`,v.titleColor,'color')}</div><div class="row">${field(k==='philosophy'?'Sentence font':'Title font',`sectionStyles.${k}.titleFont`,v.titleFont,'select',fonts)}${k==='philosophy'?'':field('Body font',`sectionStyles.${k}.bodyFont`,v.bodyFont,'select',fonts)}</div><div class="style-device-grid"><div class="device-style-card"><div class="device-style-head"><b>Desktop</b><small>1440px preview</small></div>${field(k==='philosophy'?'Sentence size':'Title size',`sectionStyles.${k}.titleSizeDesktop`,v.titleSizeDesktop,'number')}${k==='philosophy'?'':field('Body size',`sectionStyles.${k}.bodySizeDesktop`,v.bodySizeDesktop,'number')}</div><div class="device-style-card"><div class="device-style-head"><b>Mobile</b><small>390px preview</small></div>${field(k==='philosophy'?'Sentence size':'Title size',`sectionStyles.${k}.titleSizeMobile`,v.titleSizeMobile,'number')}${k==='philosophy'?'':field('Body size',`sectionStyles.${k}.bodySizeMobile`,v.bodySizeMobile,'number')}</div></div></div>`).join('')}</div></section>
<section class="panel ${activeWebsite==='hero'?'active':''}" data-panel="hero"><div class="group">${metaFields('hero',website.hero)}${imageField('Hero image','hero.image',website.hero.image)}</div></section>
<section class="panel ${activeWebsite==='philosophy'?'active':''}" data-panel="philosophy"><div class="group">${videoField('Rolling background video','philosophy.video',website.philosophy.video||'')}${imageField('Fallback background image','philosophy.image',website.philosophy.image)}${field('Video colour overlay %','philosophy.videoShade',website.philosophy.videoShade??58,'number')}${field('Eyebrow','philosophy.eyebrow',website.philosophy.eyebrow||'')}${field('Sentence 1','philosophy.title',website.philosophy.title||'','textarea')}${field('Sentence 2','philosophy.subtitle',website.philosophy.subtitle||'','textarea')}${field('Sentence 3','philosophy.body',website.philosophy.body||'','textarea')}<p class="editor-note">The video loops silently behind all sentences. Increase overlay % to soften the background and focus attention on the words.</p></div></section>
<section class="panel ${activeWebsite==='story'?'active':''}" data-panel="story"><div class="group">${metaFields('story',website.story,false)}${field('Subtitle','story.subtitle',website.story.subtitle||'','textarea')}${field('Paragraph 1','story.paragraph1',website.story.paragraph1,'textarea')}${field('Paragraph 2','story.paragraph2',website.story.paragraph2,'textarea')}${imageField('Story image','story.image',website.story.image)}</div></section>
<section class="panel ${activeWebsite==='tea'?'active':''}" data-panel="tea"><div class="group">${metaFields('tea',website.tea)}${(website.tea.items||[]).map((t,i)=>`<div class="item reorder-item" data-drop-list="tea.items" data-index="${i}"><div class="item-head"><h3>${esc(t.name)}</h3>${actions('tea.items',i)}</div>${field('Name',`tea.items.${i}.name`,t.name)}${imageField('Image',`tea.items.${i}.image`,t.image)}${field('Origin',`tea.items.${i}.origin`,t.origin)}${field('Harvest / type',`tea.items.${i}.harvest`,t.harvest)}${field('Profile',`tea.items.${i}.profile`,t.profile)}${field('Finish',`tea.items.${i}.finish`,t.finish)}</div>`).join('')}<button class="add-btn" data-add="tea.items">+ Add tea powder</button></div></section>
<section class="panel ${activeWebsite==='why'?'active':''}" data-panel="why"><div class="group">${metaFields('why',website.why,false)}${field('Subtitle','why.subtitle',website.why.subtitle||'','textarea')}${(website.why.items||[]).map((w,i)=>`<div class="item reorder-item" data-drop-list="why.items" data-index="${i}"><div class="item-head"><h3>${esc(w.title)}</h3>${actions('why.items',i)}</div>${field('Title',`why.items.${i}.title`,w.title)}${field('Description',`why.items.${i}.body`,w.body,'textarea')}</div>`).join('')}<button class="add-btn" data-add="why.items">+ Add Why Us topic</button></div></section>
<section class="panel ${activeWebsite==='library'?'active':''}" data-panel="library"><div class="group">${metaFields('library',website.library)}${(website.library.topics||[]).map((t,i)=>`<div class="item reorder-item" data-drop-list="library.topics" data-index="${i}"><div class="item-head"><h3>${esc(t.title)}</h3>${actions('library.topics',i)}</div>${field('ID',`library.topics.${i}.id`,t.id)}${field('Title',`library.topics.${i}.title`,t.title)}${field('Subtitle',`library.topics.${i}.subtitle`,t.subtitle,'textarea')}${field('Content',`library.topics.${i}.body`,t.body,'textarea')}${imageField('Image',`library.topics.${i}.image`,t.image)}</div>`).join('')}<button class="add-btn" data-add="library.topics">+ Add knowledge topic</button><h3 style="font:26px Gloock;margin-top:28px">Cultivars</h3>${(website.library.cultivars||[]).map((c,i)=>`<div class="item reorder-item" data-drop-list="library.cultivars" data-index="${i}"><div class="item-head"><h3>${esc(c.name)}</h3>${actions('library.cultivars',i)}</div>${field('Name',`library.cultivars.${i}.name`,c.name)}${field('Region',`library.cultivars.${i}.region`,c.region)}${imageField('Photo',`library.cultivars.${i}.image`,c.image)}${field('Profile',`library.cultivars.${i}.profile`,c.profile,'textarea')}<div class="row">${field('Tag 1',`library.cultivars.${i}.tag1`,c.tag1)}${field('Tag 2',`library.cultivars.${i}.tag2`,c.tag2)}</div></div>`).join('')}<button class="add-btn" data-add="library.cultivars">+ Add cultivar</button></div></section>
<section class="panel ${activeWebsite==='atlas'?'active':''}" data-panel="atlas"><div class="group">${metaFields('atlas',website.atlas)}${imageField('Japan map','atlas.mapImage',website.atlas.mapImage)}<button type="button" class="add-btn" data-restore-pins>Restore recommended pin locations</button><p class="editor-note">Recommended: Uji 68/35 · Yame 39/72 · Nishio 60/57 · Shizuoka 69/53 · Kagoshima 34/84 (X/Y).</p>${(website.atlas.regions||[]).map((r,i)=>`<div class="item reorder-item" data-drop-list="atlas.regions" data-index="${i}"><div class="item-head"><h3>${esc(r.name)}</h3>${actions('atlas.regions',i)}</div>${field('Region name',`atlas.regions.${i}.name`,r.name)}${field('Description',`atlas.regions.${i}.description`,r.description,'textarea')}${field('Style notes',`atlas.regions.${i}.notes`,r.notes)}<div class="row">${field('Pin X %',`atlas.regions.${i}.pinX`,r.pinX??50,'number')}${field('Pin Y %',`atlas.regions.${i}.pinY`,r.pinY??50,'number')}</div>${field('Cultivars (comma separated)',`atlas.regions.${i}.cultivars`,Array.isArray(r.cultivars)?r.cultivars.join(', '):r.cultivars)}</div>`).join('')}<button class="add-btn" data-add="atlas.regions">+ Add region</button></div></section>
<section class="panel ${activeWebsite==='menu'?'active':''}" data-panel="menu"><div class="group">${metaFields('menuMeta',website.menuMeta,false)}${field('Milk note','menuMeta.subtitle',website.menuMeta.subtitle||'','textarea')}${(website.menu||[]).map((m,i)=>`<div class="item reorder-item" data-drop-list="menu" data-index="${i}"><div class="item-head"><h3>${esc(m.name)}</h3>${actions('menu',i)}</div><div class="row">${field('Category',`menu.${i}.eyebrow`,m.eyebrow)}${field('Status',`menu.${i}.status`,m.status,'select',['published','draft'])}</div>${field('Name',`menu.${i}.name`,m.name)}${field('Subtitle',`menu.${i}.subtitle`,m.subtitle||'')}${field('Description',`menu.${i}.description`,m.description,'textarea')}<div class="row">${field('Price',`menu.${i}.price`,m.price)}${field('Milk option',`menu.${i}.milk`,String(m.milk),'select',['true','false'])}</div>${imageField('Photo',`menu.${i}.image`,m.image)}<div class="row">${field('Colour card',`menu.${i}.cardColor`,m.cardColor,'color')}${field('Text colour',`menu.${i}.textColor`,m.textColor,'color')}</div></div>`).join('')}<button class="add-btn" data-add="menu">+ Add drink</button></div></section>
<section class="panel ${activeWebsite==='updates'?'active':''}" data-panel="updates"><div class="group">${metaFields('updatesMeta',website.updatesMeta,false)}${field('Subtitle','updatesMeta.subtitle',website.updatesMeta.subtitle||'','textarea')}${(website.updates||[]).map((u,i)=>`<div class="item reorder-item" data-drop-list="updates" data-index="${i}"><div class="item-head"><h3>${esc(u.title)}</h3>${actions('updates',i)}</div><div class="row">${field('Date / label',`updates.${i}.date`,u.date)}${field('Status',`updates.${i}.status`,u.status,'select',['published','draft'])}</div>${field('Title',`updates.${i}.title`,u.title)}${field('Subtitle',`updates.${i}.subtitle`,u.subtitle||'')}${field('Body',`updates.${i}.body`,u.body,'textarea')}${imageField('Image',`updates.${i}.image`,u.image)}${field('Card colour',`updates.${i}.cardColor`,u.cardColor,'color')}</div>`).join('')}<button class="add-btn" data-add="updates" ${(website.updates||[]).length>=5?'disabled':''}>+ Add update (max 5)</button></div></section>
<section class="panel ${activeWebsite==='contact'?'active':''}" data-panel="contact"><div class="group">${metaFields('contact',website.contact,false)}${field('Subtitle','contact.subtitle',website.contact.subtitle||'','textarea')}<div class="item"><div class="item-head"><h3>Collection block</h3></div>${field('Label','contact.collectionLabel',website.contact.collectionLabel)}${field('Content','contact.collection',website.contact.collection,'textarea')}${field('Position','contact.positions.collection',website.contact.positions.collection,'select',['Left','Centre','Right'])}</div><div class="item"><div class="item-head"><h3>Instagram block</h3></div>${field('Label','contact.instagramLabel',website.contact.instagramLabel)}${field('Instagram display','contact.instagram',website.contact.instagram)}${field('Position','contact.positions.instagram',website.contact.positions.instagram,'select',['Left','Centre','Right'])}</div><div class="item"><div class="item-head"><h3>Orders block</h3></div>${field('Label','contact.ordersLabel',website.contact.ordersLabel)}${field('Button text','contact.orderText',website.contact.orderText)}${field('Position','contact.positions.orders',website.contact.positions.orders,'select',['Left','Centre','Right'])}</div>${field('Closing message','contact.closing',website.contact.closing,'textarea')}</div></section>`}
function renderOrderPanels(){orderPanels.innerHTML=`
<section class="panel ${activeOrder==='brand'?'active':''}" data-panel="brand"><div class="group">${field('Brand name','brand.name',order.brand.name,'text',[],'order')}${field('Instagram handle','brand.handle',order.brand.handle,'text',[],'order')}${field('Intro','brand.intro',order.brand.intro,'textarea',[],'order')}${field('Collection text','brand.collection',order.brand.collection,'textarea',[],'order')}${field('Logo','brand.logo',order.brand.logo,'image',[],'order')}<div class="row">${field('Background','brand.background',order.brand.background,'color',[],'order')}${field('Accent','brand.accent',order.brand.accent,'color',[],'order')}</div></div></section>
<section class="panel ${activeOrder==='products'?'active':''}" data-panel="products"><div class="group">${order.products.map((p,i)=>`<div class="item reorder-item" data-order-drop="products" data-index="${i}"><div class="item-head"><h3>${esc(p.name)}</h3><div class="small-actions"><button class="drag-handle" draggable="true" data-order-drag="products" data-index="${i}"><i></i><i></i><i></i><i></i><i></i><i></i></button><button class="delete" data-order-delete="products" data-index="${i}">Delete</button></div></div><div class="row">${field('Category',`products.${i}.category`,p.category,'text',[],'order')}${field('Price',`products.${i}.price`,p.price,'number',[],'order')}</div>${field('Name',`products.${i}.name`,p.name,'text',[],'order')}${field('Description',`products.${i}.description`,p.description,'textarea',[],'order')}${field('Milk option',`products.${i}.milk`,String(p.milk),'select',['true','false'],'order')}${field('Photo',`products.${i}.image`,p.image,'image',[],'order')}</div>`).join('')}<button class="add-btn" data-order-add="products">+ Add product</button></div></section>
<section class="panel ${activeOrder==='options'?'active':''}" data-panel="options"><div class="group">${field('Ice options (comma separated)','options.ice',order.options.ice.join(', '),'text',[],'order')}${field('Sweetness (comma separated)','options.sweetness',order.options.sweetness.join(', '),'text',[],'order')}${field('Milk options (comma separated)','options.milk',order.options.milk.join(', '),'text',[],'order')}</div></section>
<section class="panel ${activeOrder==='collection'?'active':''}" data-panel="collection"><div class="group">${field('Label','schedule.label',order.schedule.label,'text',[],'order')}${field('Days','schedule.day',order.schedule.day,'text',[],'order')}${field('Times (comma separated)','schedule.times',order.schedule.times.join(', '),'text',[],'order')}</div></section>
<section class="panel ${activeOrder==='promo'?'active':''}" data-panel="promo"><div class="group">${field('Promo code','promo.code',order.promo.code,'text',[],'order')}${field('Discount %','promo.discount',order.promo.discount,'number',[],'order')}</div></section>`}
function updateHeaders(){const current=mode==='website'?websiteSections.find(x=>x[1]===activeWebsite):orderSections.find(x=>x[1]===activeOrder);$('#panelTitle').textContent=current?.[0]||'';$('#previewTitle').textContent=mode==='website'?'Website preview':'Ordering preview'}
function renderAll(){renderNav();renderWebsitePanels();renderOrderPanels();updateHeaders();bindImageMiniButtons()}
function preview(){if(mode==='website')frame.contentWindow.postMessage({type:'SHIZUKU_PREVIEW',data:website},'*');else frame.contentWindow.postMessage({type:'ORDER_PREVIEW',data:order},'*')}
function navigate(){if(mode==='website'){const target=websiteSections.find(x=>x[1]===activeWebsite)?.[2];setTimeout(()=>frame.contentWindow.postMessage({type:'SHIZUKU_NAVIGATE',target},'*'),80)}else{const target=orderSections.find(x=>x[1]===activeOrder)?.[2];setTimeout(()=>frame.contentWindow.postMessage({type:'ORDER_NAVIGATE',target},'*'),80)}}
function switchMode(next){mode=next;shell.classList.toggle('order-mode',mode==='ordering');document.querySelectorAll('.mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));frame.src=mode==='website'?'shizuku-website.html?cms=1':'order-preview.html?cms=1';updateHeaders();frame.onload=()=>{preview();navigate()}}
document.querySelector('.mode-tabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(b)switchMode(b.dataset.mode)};
$('#websiteNav').onclick=e=>{const b=e.target.closest('[data-web-panel]');if(!b)return;activeWebsite=b.dataset.webPanel;renderAll();navigate()};$('#orderNav').onclick=e=>{const b=e.target.closest('[data-order-panel]');if(!b)return;activeOrder=b.dataset.orderPanel;renderAll();navigate()};
function dirty(){saveStatus.textContent='Unsaved changes';saveStatus.style.background='#fff1d8'}
function normalizeArrayPath(scope,path,val){if(scope==='order'&&['options.ice','options.sweetness','options.milk','schedule.times'].includes(path))return val.split(',').map(x=>x.trim()).filter(Boolean);if(scope==='website'&&/atlas\.regions\.\d+\.cultivars/.test(path))return val.split(',').map(x=>x.trim()).filter(Boolean);return null}
document.addEventListener('input',e=>{const path=e.target.dataset.path,scope=e.target.dataset.scope;if(!path)return;if(e.target.type==='number'&&e.target.value===''){dirty();return}const arr=normalizeArrayPath(scope,path,e.target.value);if(scope==='website')arr?set(website,path,arr):set(website,path,e.target.value);else arr?set(order,path,arr):set(order,path,e.target.value);dirty();preview()});
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>res(r.result);r.readAsDataURL(file)})}
document.addEventListener('change',async e=>{if(e.target.dataset.websiteImage){const f=e.target.files?.[0];if(!f)return;set(website,e.target.dataset.websiteImage,await fileToData(f));renderAll();dirty();preview()}if(e.target.dataset.websiteVideo){const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){alert('Please use a video under 8MB.');e.target.value='';return}set(website,e.target.dataset.websiteVideo,await fileToData(f));renderAll();dirty();preview()}if(e.target.dataset.orderImage){const f=e.target.files?.[0];if(!f)return;set(order,e.target.dataset.orderImage,await fileToData(f));renderAll();dirty();preview()}});
const templates={'why.items':{title:'New detail',body:'Describe why it matters.'},'tea.items':{name:'New tea',image:'assets/straight-matcha.jpg',origin:'Japan',harvest:'',profile:'',finish:''},'library.topics':{id:'topic-'+Date.now(),title:'New topic',subtitle:'',body:'',image:'assets/straight-matcha.jpg'},'library.cultivars':{name:'New cultivar',region:'Japan',image:'assets/straight-matcha.jpg',profile:'',tag1:'',tag2:''},'atlas.regions':{name:'New region',description:'',cultivars:[],notes:'',pinX:50,pinY:50},'menu':{eyebrow:'NEW',name:'New drink',subtitle:'',description:'',price:'$0.00',milk:true,image:'assets/matcha-latte.jpg',cardColor:'#dcebcf',textColor:'#173e31',status:'draft'},'updates':{date:'FROM THE LAB',title:'New update',subtitle:'',body:'',image:'assets/matcha-latte.jpg',cardColor:'#e9e2d4',status:'draft'}};
document.addEventListener('click',e=>{const picker=e.target.closest('[data-image-pick]');if(picker){document.querySelector(picker.dataset.imagePick)?.click();return}const rmv=e.target.closest('[data-video-remove]');if(rmv){set(website,rmv.dataset.videoRemove,'');renderAll();dirty();preview();return}const rmw=e.target.closest('[data-image-remove-website]');if(rmw){set(website,rmw.dataset.imageRemoveWebsite,'');renderAll();dirty();preview();return}const rmo=e.target.closest('[data-image-remove-order]');if(rmo){set(order,rmo.dataset.imageRemoveOrder,'');renderAll();dirty();preview();return}const add=e.target.closest('[data-add]');if(add){if(add.dataset.add==='updates'&&website.updates.length>=5)return;get(website,add.dataset.add).push(clone(templates[add.dataset.add]));renderAll();dirty();preview();return}const del=e.target.closest('[data-delete]');if(del){get(website,del.dataset.delete).splice(+del.dataset.index,1);renderAll();dirty();preview();return}const oa=e.target.closest('[data-order-add]');if(oa){order.products.push({category:'NEW',name:'New product',price:0,description:'',image:'assets/matcha-latte.jpg',milk:true});renderAll();dirty();preview();return}const od=e.target.closest('[data-order-delete]');if(od){order.products.splice(+od.dataset.index,1);renderAll();dirty();preview();return}const reset=e.target.closest('[data-image-reset]');if(reset){const field=reset.closest('[data-image-field]'),base=reset.dataset.imageReset,obj=get(website,base),dev=field?.dataset.imageDevice||'desktop';if(dev==='mobile'){obj.imagePositionMobile={x:50,y:50};obj.imageScaleMobile=1}else{obj.imagePositionDesktop={x:50,y:50};obj.imageScaleDesktop=1}renderAll();dirty();preview();return}});
document.addEventListener('click',e=>{if(!e.target.closest('[data-restore-pins]'))return;const recommended={'Uji, Kyoto':[68,35],'Yame, Fukuoka':[39,72],'Nishio, Aichi':[60,57],'Shizuoka':[69,53],'Kagoshima':[34,84]};(website.atlas.regions||[]).forEach(region=>{const pin=recommended[region.name];if(pin){region.pinX=pin[0];region.pinY=pin[1]}});renderAll();dirty();preview()});
// logo position pad
let padDrag=null;function movePad(p,x,y){const r=p.getBoundingClientRect(),mx=Math.max(0,Math.min(100,(x-r.left)/r.width*100)),my=Math.max(0,Math.min(100,(y-r.top)/r.height*100)),px=mx*1.5-25,py=my*1.5-25;set(website,p.dataset.positionPad,{x:px,y:py});p.querySelector('b').style.left=mx+'%';p.querySelector('b').style.top=my+'%';p.closest('.field')?.querySelectorAll('.position-values input').forEach((el,i)=>el.value=(i?py:px).toFixed(1));dirty();preview()}
document.addEventListener('pointerdown',e=>{const p=e.target.closest('[data-position-pad]');if(p){padDrag=p;p.setPointerCapture(e.pointerId);movePad(p,e.clientX,e.clientY);return}const box=e.target.closest('[data-image-editor]');if(box){const field=box.closest('[data-image-field]'),base=box.dataset.imageEditor,dev=field.dataset.imageDevice,obj=get(website,base),pos=dev==='mobile'?(obj.imagePositionMobile||{x:50,y:50}):(obj.imagePositionDesktop||{x:50,y:50});window.__imgDrag={box,field,base,dev,sx:e.clientX,sy:e.clientY,x:+pos.x||50,y:+pos.y||50};box.setPointerCapture(e.pointerId);box.classList.add('dragging')}});
document.addEventListener('pointermove',e=>{if(padDrag){movePad(padDrag,e.clientX,e.clientY);return}const d=window.__imgDrag;if(!d)return;const r=d.box.getBoundingClientRect(),x=Math.max(0,Math.min(100,d.x-(e.clientX-d.sx)/r.width*100)),y=Math.max(0,Math.min(100,d.y-(e.clientY-d.sy)/r.height*100)),obj=get(website,d.base);if(d.dev==='mobile')obj.imagePositionMobile={x,y};else obj.imagePositionDesktop={x,y};const im=d.box.querySelector('img');im.style.objectPosition=`${x}% ${y}%`;im.style.transformOrigin=`${x}% ${y}%`;dirty();preview()});document.addEventListener('pointerup',e=>{padDrag=null;if(window.__imgDrag){window.__imgDrag.box.classList.remove('dragging');window.__imgDrag=null}});
document.addEventListener('input',e=>{const base=e.target.dataset.imageScale;if(!base)return;const field=e.target.closest('[data-image-field]'),dev=field.dataset.imageDevice,obj=get(website,base),v=+e.target.value;if(dev==='mobile')obj.imageScaleMobile=v;else obj.imageScaleDesktop=v;field.querySelector('.image-crop img').style.transform=`scale(${v})`;dirty();preview()});
function bindImageMiniButtons(){document.querySelectorAll('[data-img-device]').forEach(b=>b.onclick=()=>{const field=b.closest('[data-image-field]'),base=field.dataset.imageField,obj=get(website,base),dev=b.dataset.imgDevice;field.dataset.imageDevice=dev;field.querySelectorAll('[data-img-device]').forEach(x=>x.classList.toggle('active',x===b));const pos=dev==='mobile'?(obj.imagePositionMobile||obj.imagePosition||{x:50,y:50}):(obj.imagePositionDesktop||obj.imagePosition||{x:50,y:50}),scale=dev==='mobile'?(obj.imageScaleMobile??obj.imageScale??1):(obj.imageScaleDesktop??obj.imageScale??1),im=field.querySelector('.image-crop img');im.style.objectPosition=`${pos.x}% ${pos.y}%`;im.style.transformOrigin=`${pos.x}% ${pos.y}%`;im.style.transform=`scale(${scale})`;field.querySelector('[data-image-scale]').value=scale})}
// drag reorder
let drag=null;document.addEventListener('dragstart',e=>{const h=e.target.closest('[data-drag-list]');if(h){drag={scope:'website',list:h.dataset.dragList,index:+h.dataset.index};h.closest('.reorder-item')?.classList.add('dragging')}const oh=e.target.closest('[data-order-drag]');if(oh){drag={scope:'order',list:'products',index:+oh.dataset.index};oh.closest('.reorder-item')?.classList.add('dragging')}});document.addEventListener('dragover',e=>{const it=e.target.closest('[data-drop-list],[data-order-drop]');if(!it||!drag)return;e.preventDefault();it.classList.add('drag-over')});document.addEventListener('dragleave',e=>e.target.closest('.reorder-item')?.classList.remove('drag-over'));document.addEventListener('drop',e=>{const it=e.target.closest('[data-drop-list],[data-order-drop]');if(!it||!drag)return;e.preventDefault();const to=+it.dataset.index,a=drag.scope==='website'?get(website,drag.list):order.products;if(to!==drag.index){const [m]=a.splice(drag.index,1);a.splice(to,0,m)}drag=null;renderAll();dirty();preview()});document.addEventListener('dragend',()=>{drag=null;document.querySelectorAll('.dragging,.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'))});
// IndexedDB draft storage
const DB='slow-studio-cms',STORE='drafts',LOCAL_PREFIX='slow-studio-cms:';
function localPut(key,val){try{localStorage.setItem(LOCAL_PREFIX+key,JSON.stringify(val));return true}catch(e){console.warn('Local storage unavailable',e);return false}}
function localGet(key){try{const raw=localStorage.getItem(LOCAL_PREFIX+key);return raw?JSON.parse(raw):null}catch(e){console.warn('Local storage unavailable',e);return null}}
function localDel(key){try{localStorage.removeItem(LOCAL_PREFIX+key)}catch(e){console.warn(e)}}
function db(){return new Promise((res,rej)=>{if(!window.indexedDB)return rej(new Error('IndexedDB unavailable'));const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(key,val){const localSaved=localPut(key,val);try{const d=await db();await new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(val,key);t.oncomplete=res;t.onerror=()=>rej(t.error)});d.close();return true}catch(e){console.warn('IndexedDB save unavailable; using local fallback',e);if(!localSaved)throw e;return true}}
async function getDraft(key){try{const d=await db(),value=await new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});d.close();return value||localGet(key)}catch(e){console.warn('IndexedDB load unavailable; using local fallback',e);return localGet(key)}}
async function delDraft(key){localDel(key);try{const d=await db();await new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(key);t.oncomplete=res;t.onerror=()=>rej(t.error)});d.close()}catch(e){console.warn('IndexedDB delete unavailable',e)}}
const cloud=window.ShizukuCloud;
const cloudBtn=$('#cloudAuthBtn'),cloudDialog=$('#cloudDialog'),cloudEmail=$('#cloudEmail'),cloudPassword=$('#cloudPassword'),cloudError=$('#cloudError');
async function refreshCloudStatus(){
  if(!cloud?.configured){cloudBtn.textContent='Cloud · Not configured';return null}
  const user=await cloud.currentUser();
  cloudBtn.classList.toggle('online',!!user);
  cloudBtn.textContent=user?'Cloud · Connected':'Cloud · Sign in';
  return user;
}
function openCloudLogin(message=''){cloudError.textContent=message;cloudPassword.value='';cloudDialog.showModal();setTimeout(()=>cloudPassword.focus(),50)}
cloudBtn.onclick=async()=>{const user=await refreshCloudStatus();if(user){if(confirm(`Signed in as ${user.email}. Sign out?`)){await cloud.signOut();await refreshCloudStatus()}}else openCloudLogin()};
$('#cloudCancel').onclick=()=>cloudDialog.close();
$('#cloudLogin').onclick=async()=>{cloudError.textContent='Signing in…';try{await cloud.signIn(cloudEmail.value,cloudPassword.value);cloudDialog.close();await refreshCloudStatus();saveStatus.textContent='Cloud connected ✓';const remote=await cloud.loadDraft().catch(()=>null);if(remote?.data&&confirm('A cloud draft exists. Load it now?')){website=remote.data;ensureStyleDefaults(website);renderAll();preview();}}catch(err){cloudError.textContent=err.message||String(err)}};
$('#saveDraft').onclick=async()=>{
  saveStatus.textContent='Saving…';
  try{await put('shizuku-workspace',{website,order,savedAt:new Date().toISOString()});saveStatus.textContent='Saved on this device ✓';saveStatus.style.background='#edf2e9'}catch(err){saveStatus.textContent='Save failed';alert('The browser blocked local storage. Please open CMS through a local/server URL or use Export Backup.\n\n'+(err.message||err));return}
  const user=await refreshCloudStatus().catch(()=>null);
  if(user){try{await cloud.saveDraft(website);saveStatus.textContent='Cloud draft saved ✓';saveStatus.style.background='#edf2e9'}catch(err){saveStatus.textContent='Saved locally';alert('Local draft saved, but cloud save failed: '+err.message)}}
  else{saveStatus.textContent='Saved locally · sign in for cloud';saveStatus.style.background='#fff3d6'}
};
$('#resetDraft').onclick=async()=>{if(!confirm('Reset the local draft to the packaged data?'))return;await delDraft('shizuku-workspace');location.reload()};
$('#publish').onclick=async()=>{
  const user=await refreshCloudStatus();
  if(!user){openCloudLogin('Sign in first, then press Publish Website again.');return}
  saveStatus.textContent='Compacting & publishing…';
  try{await cloud.publish(website);await put('shizuku-published',{website,publishedAt:new Date().toISOString()});saveStatus.textContent='Published live ✓';saveStatus.style.background='#dfe8d9';alert('Published. The live website now reads this version from Supabase.');}
  catch(err){saveStatus.textContent='Publish failed';alert('Could not publish. If this is the first setup, run SUPABASE-WEBSITE-CMS.sql in Supabase SQL Editor first.\n\n'+(err.message||err));}
};
$('#exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify({website,order},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shizuku-workspace-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
let previewDevice='desktop',previewScale='actual';function sizePreview(){const wrap=$('#framewrap');if(!wrap)return;wrap.className='framewrap '+(previewDevice==='mobile'?'mobile':previewScale);if(previewDevice==='mobile'||previewScale==='actual'){frame.style.transform='none';frame.style.height='100%';return}const scale=Math.min(1,wrap.clientWidth/1440);frame.style.transform=`scale(${scale})`;frame.style.height=(100/scale)+'%'}document.querySelector('.devices').onclick=e=>{const b=e.target.closest('[data-device]');if(!b)return;previewDevice=b.dataset.device;document.querySelectorAll('.devices button').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('.preview-scale').style.visibility=previewDevice==='desktop'?'visible':'hidden';sizePreview()};document.querySelector('.preview-scale').onclick=e=>{const b=e.target.closest('[data-preview-scale]');if(!b)return;previewScale=b.dataset.previewScale;document.querySelectorAll('[data-preview-scale]').forEach(x=>x.classList.toggle('active',x===b));sizePreview()};window.addEventListener('resize',sizePreview);

function setUnifiedWorkspace(which){
 document.querySelectorAll('[data-workspace]').forEach(b=>b.classList.toggle('active',b.dataset.workspace===which));
 if(which==='preview'){window.open('/shop/shizuku-lab-sg','_blank');setUnifiedWorkspace('website');return}
 if(which==='website'){shell.classList.remove('external-mode');$('#orderWorkspace').hidden=true;sizePreview();return}
 shell.classList.add('external-mode');$('#orderWorkspace').hidden=false;
 const f=$('#orderAdminFrame');
 const tab=which==='orders'?'orders':'menu';
 const send=()=>f.contentWindow?.postMessage({type:'SHIZUKU_ADMIN_TAB',tab},'*');
 try{send()}catch(e){};setTimeout(send,250);
}
document.querySelector('.mode-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-workspace]');if(b)setUnifiedWorkspace(b.dataset.workspace)});
(async()=>{
 try{
   await refreshCloudStatus();
   const user=await cloud?.currentUser();
   if(user){
     const remote=await cloud.loadDraft().catch(err=>{console.warn('Cloud draft unavailable',err);return null});
     if(remote?.data){website=remote.data;ensureStyleDefaults(website);saveStatus.textContent='Cloud draft loaded ✓'}
     else{
       const saved=await getDraft('shizuku-workspace');if(saved){website=saved.website||website;order=saved.order||order;ensureStyleDefaults(website);saveStatus.textContent='Local draft restored ✓'}
     }
   }else{
     const saved=await getDraft('shizuku-workspace');if(saved){website=saved.website||website;order=saved.order||order;ensureStyleDefaults(website);saveStatus.textContent='Local draft restored ✓'}
   }
 }catch(e){console.warn(e)}
 renderAll();sizePreview();frame.onload=()=>{preview();navigate();sizePreview()}
})();
})();
