(function(){
const clone=x=>JSON.parse(JSON.stringify(x));
let data=clone(window.SHIZUKU_DATA);
function ensureDefaults(){const styles=data.sectionStyles||{};Object.values(styles).forEach(v=>{if(v.bodySizeDesktop==null)v.bodySizeDesktop=Number(v.bodySize??16);if(v.bodySizeMobile==null)v.bodySizeMobile=Number(v.bodySize??v.bodySizeDesktop??16);if(v.titleSizeDesktop==null)v.titleSizeDesktop=Number(v.titleSize??72);if(v.titleSizeMobile==null)v.titleSizeMobile=Number(v.titleSizeDesktop??48)});data.textStyles=data.textStyles||{};data.brand.navLabels=data.brand.navLabels||{story:'Our Story',tea:'Our Tea',why:'Why Us',library:'Tea Library',menu:'Menu',updates:'From the Lab',contact:'Contact',order:'Reserve your cup'};data.philosophy.image=data.philosophy.image||data.hero.image;data.philosophy.videoShade=Number(data.philosophy.videoShade??58);data.atlas=data.atlas||{eyebrow:'MATCHA ATLAS',title:'Explore Japan through tea.',subtitle:'Regions, styles and cultivars in one place.',body:'Select a region to discover its tea character and related cultivars.',mapImage:'assets/japan-map.svg',regions:[{name:'Uji, Kyoto',description:'Historic tea region known for refined aroma, umami and elegant texture.',cultivars:['Uji Midori','Samidori','Gokou','Asahi'],notes:'Refined · Umami · Aromatic'},{name:'Yame, Fukuoka',description:'Known for shaded teas with depth, sweetness and a smooth finish.',cultivars:['Yabukita','Okumidori'],notes:'Deep · Sweet · Smooth'},{name:'Nishio, Aichi',description:'A major matcha-producing area with a rich body and approachable balance.',cultivars:['Yabukita','Samidori'],notes:'Rich · Balanced · Full-bodied'},{name:'Shizuoka',description:'Japan’s largest tea-producing prefecture, offering a broad range of styles.',cultivars:['Yabukita','Okuyutaka'],notes:'Fresh · Green · Versatile'}]};const migrate=o=>{if(!o||typeof o!=='object')return;if(o.image){if(!o.imagePositionDesktop)o.imagePositionDesktop=o.imagePosition||{x:50,y:50};if(!o.imagePositionMobile)o.imagePositionMobile=o.imagePosition||{x:50,y:50};if(o.imageScaleDesktop==null)o.imageScaleDesktop=o.imageScale||1;if(o.imageScaleMobile==null)o.imageScaleMobile=o.imageScale||1;}Object.values(o).forEach(v=>{if(Array.isArray(v))v.forEach(migrate);else if(v&&typeof v==='object')migrate(v)})};migrate(data)}
ensureDefaults();
const site=document.getElementById('site'),nav=document.getElementById('nav'),mobileNav=document.getElementById('mobileNav');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nl=s=>esc(s).replace(/\n/g,'<br>');
const pathGet=(root,path)=>path.split('.').reduce((o,k)=>o?.[k],root);
const pathSet=(root,path,value)=>{const keys=path.split('.');let cursor=root;keys.slice(0,-1).forEach(k=>cursor=cursor[k]||(cursor[k]={}));cursor[keys.at(-1)]=value};
const imageVars=o=>{const pd=o?.imagePositionDesktop||o?.imagePosition||{x:50,y:50},pm=o?.imagePositionMobile||o?.imagePosition||{x:50,y:50},sd=Number(o?.imageScaleDesktop??o?.imageScale??1),sm=Number(o?.imageScaleMobile??o?.imageScale??1);return `--img-x-d:${Number(pd.x??50)}%;--img-y-d:${Number(pd.y??50)}%;--img-s-d:${sd};--img-x-m:${Number(pm.x??50)}%;--img-y-m:${Number(pm.y??50)}%;--img-s-m:${sm};`};
const img=(src,alt,cls='',owner=null)=>`<img class="${cls} managed-image" src="${esc(src)}" alt="${esc(alt)}" style="${imageVars(owner)}">`;
function fontVars(key){const s=data.sectionStyles[key]||{};return `--section-bg:${s.background};--title-font:'${s.titleFont}',serif;--title-desktop:${s.titleSizeDesktop}px;--title-mobile:${s.titleSizeMobile}px;--body-font:'${s.bodyFont}',sans-serif;--body-desktop:${Number(s.bodySizeDesktop??s.bodySize??16)}px;--body-mobile:${Number(s.bodySizeMobile??s.bodySizeDesktop??s.bodySize??16)}px;--title-color:${s.titleColor};--body-color:${s.bodyColor};`}
function titleBlock(meta,chapter){return `<div class="section-head"><p class="eyebrow">${esc(meta.eyebrow||chapter||'')}</p><h2>${nl(meta.title)}</h2>${meta.subtitle?`<p class="subtitle">${esc(meta.subtitle)}</p>`:''}</div>`}
function render(){
 if(data.philosophy.video==null)data.philosophy.video='assets/philosophy-matcha-pour.mp4';
 ['tea.items','why.items','library.topics','library.cultivars','atlas.regions','menu','updates'].forEach(path=>{const current=pathGet(data,path),fallback=pathGet(window.SHIZUKU_DATA,path);if((!Array.isArray(current)||current.length===0)&&Array.isArray(fallback)&&fallback.length)pathSet(data,path,clone(fallback))});
 data.contact.collectionLabel??='Collection';data.contact.instagramLabel??='Instagram';data.contact.ordersLabel??='Orders';data.contact.orderText??='Reserve your cup ↗';data.contact.positions=data.contact.positions||{collection:'Left',instagram:'Centre',orders:'Right'};
 const __scrollY=window.scrollY;
 document.documentElement.style.setProperty('--ink',data.brand.ink);document.documentElement.style.setProperty('--forest',data.brand.forest);document.documentElement.style.setProperty('--paper',data.brand.paper);document.documentElement.style.setProperty('--accent',data.brand.accent);document.documentElement.style.setProperty('--logo-color',data.brand.logoColor);document.documentElement.style.setProperty('--logo-desktop',data.brand.logoDesktop+'px');document.documentElement.style.setProperty('--logo-mobile',data.brand.logoMobile+'px');document.documentElement.style.setProperty('--logo-x-desktop',(data.brand.logoDesktopPosition?.x??6)+'%');document.documentElement.style.setProperty('--logo-y-desktop',(data.brand.logoDesktopPosition?.y??50)+'%');document.documentElement.style.setProperty('--logo-x-mobile',(data.brand.logoMobilePosition?.x??10)+'%');document.documentElement.style.setProperty('--logo-y-mobile',(data.brand.logoMobilePosition?.y??50)+'%');document.documentElement.style.setProperty('--logo-url',`url("${data.brand.logo}")`);
 const labels=data.brand.navLabels,links=[['story',labels.story],['tea',labels.tea],['why',labels.why],['library',labels.library],['menu',labels.menu],['updates',labels.updates],['contact',labels.contact]];
 nav.innerHTML=links.map(([id,label])=>`<a href="#${id}">${esc(label)}</a>`).join('');mobileNav.innerHTML=nav.innerHTML+`<a href="${esc(data.brand.orderUrl)}" target="_blank">${esc(labels.order)} ↗</a>`;document.getElementById('headerOrder').textContent=labels.order;document.getElementById('headerOrder').href=data.brand.orderUrl;
 const whyItems=data.why.items||[],topics=data.library.topics||[],cultivars=data.library.cultivars||[],menuItems=(data.menu||[]).filter(x=>x.status!=='draft'),updates=(data.updates||[]).filter(x=>x.status!=='draft').slice(0,5);
 site.innerHTML=`
 <section id="home" class="hero section-theme" style="${fontVars('hero')}"><div class="hero-media">${img(data.hero.image,data.hero.title,'',data.hero)}</div><div class="hero-overlay"></div><div class="hero-copy"><p class="eyebrow">${esc(data.hero.eyebrow)}</p><h1>${esc(data.hero.title)}<br><em>${esc(data.hero.subtitle)}</em></h1><p>${esc(data.hero.body)}</p></div><a class="scroll-cue" href="#philosophy">Scroll to discover <i></i></a></section>
 <section id="philosophy" class="philosophy section-theme" style="${fontVars('philosophy')}--video-shade:${Math.max(0,Math.min(100,data.philosophy.videoShade)) / 100}"><div class="philosophy-sticky"><div class="philosophy-media">${img(data.philosophy.image,data.philosophy.eyebrow,'',data.philosophy)}${data.philosophy.video?`<video src="${esc(data.philosophy.video)}" muted loop autoplay playsinline preload="metadata" poster="${esc(data.philosophy.image)}"></video>`:''}</div><div class="philosophy-shade"></div><p class="eyebrow philosophy-eyebrow">${esc(data.philosophy.eyebrow)}</p><div class="philosophy-copy">${[data.philosophy.title,data.philosophy.subtitle,data.philosophy.body].filter(Boolean).map((sentence,i)=>`<p class="philosophy-line${i===0?' is-active':''}">${nl(sentence)}</p>`).join('')}</div></div><div class="philosophy-sequence">${[data.philosophy.title,data.philosophy.subtitle,data.philosophy.body].filter(Boolean).map((sentence,i)=>`<div class="philosophy-step" data-step="${i}" aria-label="${esc(sentence)}"></div>`).join('')}</div></section>
 <section id="story" class="story section-theme" style="${fontVars('story')}"><div class="story-grid section-inner"><div class="portrait-media">${img(data.story.image,data.story.title,'',data.story)}</div><div>${titleBlock(data.story)}<p>${esc(data.story.paragraph1)}</p><p>${esc(data.story.paragraph2)}</p></div></div></section>
 <section id="tea" class="tea section-theme" style="${fontVars('tea')}"><div class="section-inner">${titleBlock(data.tea)}<p class="wide-body">${esc(data.tea.body)}</p><div class="tea-grid">${(data.tea.items||[]).map(t=>`<article class="tea-card"><div class="tea-image">${img(t.image,t.name,'',t)}</div><div><h3>${esc(t.name)}</h3><dl><div><dt>Origin</dt><dd>${esc(t.origin)}</dd></div><div><dt>Harvest</dt><dd>${esc(t.harvest)}</dd></div><div><dt>Profile</dt><dd>${esc(t.profile)}</dd></div><div><dt>Finish</dt><dd>${esc(t.finish)}</dd></div></dl></div></article>`).join('')}</div></div></section>
 <section id="why" class="why section-theme" style="${fontVars('why')}"><div class="section-inner">${titleBlock(data.why)}<div class="why-list">${whyItems.map((w,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(w.title)}</h3><p>${esc(w.body)}</p></article>`).join('')}</div></div></section>
 <section id="library" class="library section-theme" style="${fontVars('library')}"><div class="section-inner">${titleBlock(data.library)}<p class="wide-body">${esc(data.library.body)}</p><div class="topic-grid">${topics.map((t,i)=>`<button class="topic-card" data-topic="${esc(t.id)}"><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(t.title)}</h3><p>${esc(t.subtitle)}</p><i>Explore ↗</i></button>`).join('')}</div><div class="atlas-block"><div class="atlas-copy">${titleBlock(data.atlas)}<p class="wide-body">${esc(data.atlas.body)}</p></div><div class="atlas-layout"><div class="atlas-map"><img src="${esc(data.atlas.mapImage)}" alt="Map of Japan tea regions">${(data.atlas.regions||[]).map((r,i)=>`<span class="atlas-pin" style="--pin-x:${Number(r.pinX??50)}%;--pin-y:${Number(r.pinY??50)}%">${i+1}</span>`).join('')}</div><div class="atlas-regions">${(data.atlas.regions||[]).map((r,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h4>${esc(r.name)}</h4><p>${esc(r.description)}</p><small>${esc(r.notes)}</small><div class="atlas-cultivars">${(Array.isArray(r.cultivars)?r.cultivars:String(r.cultivars||'').split(',')).map(c=>`<button type="button" data-cultivar-name="${esc(c.trim())}">${esc(c.trim())}</button>`).join('')}</div></article>`).join('')}</div></div></div><div class="cultivar-head"><p class="eyebrow">CULTIVAR COLOUR STUDY</p><h3>One powder at a time.</h3></div><div class="cultivar-grid">${cultivars.map(c=>`<article class="cultivar-card"><div>${img(c.image,c.name,'',c)}</div><h4>${esc(c.name)}</h4><small>${esc(c.region)}</small><p>${esc(c.profile)}</p><span>${esc(c.tag1)}</span><span>${esc(c.tag2)}</span></article>`).join('')}</div></div></section>
 <section id="menu" class="menu section-theme" style="${fontVars('menu')}"><div class="section-inner">${titleBlock(data.menuMeta)}<div class="menu-list">${menuItems.map((m,i)=>`<article class="menu-card" style="--card:${m.cardColor};--card-text:${m.textColor}"><div class="menu-photo">${img(m.image,m.name,'',m)}</div><div class="colour-card"><p class="eyebrow">${esc(m.eyebrow)}</p><h3>${esc(m.name)}</h3>${m.subtitle?`<h4>${esc(m.subtitle)}</h4>`:''}<p>${esc(m.description)}</p><strong>${esc(m.price)}</strong>${m.milk?`<small>Oat milk (default) · NOBO soy available</small>`:''}</div></article>`).join('')}</div><a class="big-cta" href="${esc(data.brand.orderUrl)}" target="_blank">View full menu & order ↗</a></div></section>
 <section id="updates" class="updates section-theme" style="${fontVars('updates')}"><div class="section-inner">${titleBlock(data.updatesMeta)}<div class="update-grid">${updates.map(u=>`<article style="--update-card:${u.cardColor}"><div>${img(u.image,u.title,'',u)}</div><small>${esc(u.date)}</small><h3>${esc(u.title)}</h3>${u.subtitle?`<h4>${esc(u.subtitle)}</h4>`:''}<p>${esc(u.body)}</p></article>`).join('')}</div></div></section>
 <section id="contact" class="contact section-theme" style="${fontVars('contact')}"><div class="section-inner">${titleBlock(data.contact)}<div class="contact-grid"><div class="contact-item" style="--contact-column:${({Left:1,Centre:2,Right:3})[data.contact.positions.collection]||1}"><span>${esc(data.contact.collectionLabel)}</span><p>${nl(data.contact.collection)}</p></div><div class="contact-item" style="--contact-column:${({Left:1,Centre:2,Right:3})[data.contact.positions.instagram]||2}"><span>${esc(data.contact.instagramLabel)}</span><a href="${esc(data.brand.instagramUrl)}" target="_blank">${esc(data.contact.instagram)}</a></div><div class="contact-item" style="--contact-column:${({Left:1,Centre:2,Right:3})[data.contact.positions.orders]||3}"><span>${esc(data.contact.ordersLabel)}</span><a href="${esc(data.brand.orderUrl)}" target="_blank">${esc(data.contact.orderText)}</a></div></div><div class="closing"><span class="logo-mark"></span><p>${esc(data.contact.closing)}</p></div></div></section><footer><span>© 2026 SHIZUKU LAB</span><span>POWERED BY SLOW STUDIO</span></footer>`;
 applyTextStyles();
 bindTopics();
 initScrollMedia();
 initPhilosophySequence();
 requestAnimationFrame(()=>window.scrollTo(0,__scrollY));
}

function initPhilosophySequence(){
 const steps=[...document.querySelectorAll('.philosophy-step')];
 const lines=[...document.querySelectorAll('.philosophy-line')];
 const section=document.getElementById('philosophy'),media=section?.querySelector('.philosophy-media');
 if(!steps.length)return;
 let ticking=false;
 const update=()=>{const r=section.getBoundingClientRect(),travel=Math.max(1,section.offsetHeight-innerHeight),progress=Math.max(0,Math.min(.999,-r.top/travel)),active=Math.min(lines.length-1,Math.floor(progress*lines.length));media?.style.setProperty('--roll-zoom',String(1+progress*.1));lines.forEach((line,i)=>line.classList.toggle('is-active',i===active));ticking=false};
 const requestUpdate=()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}};
 update();window.addEventListener('scroll',requestUpdate,{passive:true});window.addEventListener('resize',requestUpdate,{passive:true});
}

function walkStrings(o,p='',out=new Map()){if(!o||typeof o!=='object')return out;Object.entries(o).forEach(([k,v])=>{const path=p?`${p}.${k}`:k;if(typeof v==='string'&&v.trim()){const list=out.get(v.trim())||[];list.push(path);out.set(v.trim(),list)}else if(v&&typeof v==='object')walkStrings(v,path,out)});return out}
function styleForPath(path){return path.split('.').reduce((o,k)=>o?.[k],data.textStyles)||null}
function applyTextStyles(){const strings=walkStrings(data);document.querySelectorAll('body *').forEach(el=>{[...el.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim()).forEach(node=>{const paths=strings.get(node.textContent.trim());if(!paths)return;const path=paths.find(p=>styleForPath(p));if(!path)return;const s=styleForPath(path),span=document.createElement('span');span.className='cms-text-style';span.style.setProperty('--cms-font',s.font?`'${s.font}'`:'inherit');if(s.desktop)span.style.setProperty('--cms-size-d',Math.max(6,Math.min(120,Number(s.desktop)))+'px');if(s.mobile)span.style.setProperty('--cms-size-m',Math.max(6,Math.min(68,Number(s.mobile)))+'px');span.textContent=node.textContent;node.replaceWith(span)})})}
function initScrollMedia(){if(!('IntersectionObserver' in window))return;const boxes=[...document.querySelectorAll('.hero-media,.portrait-media,.tea-image,.topic-card,.atlas-map,.cultivar-card>div,.menu-photo,.update-grid article>div')];const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('scroll-media-active',e.isIntersecting)),{threshold:.3});boxes.forEach(x=>{x.classList.add('scroll-media');observer.observe(x)})}

function bindTopics(){document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic));document.querySelectorAll('[data-cultivar-name]').forEach(b=>b.onclick=()=>openCultivar(b.dataset.cultivarName));}
function openTopic(id){const t=(data.library.topics||[]).find(x=>x.id===id);if(!t)return;document.getElementById('drawerContent').innerHTML=`<p class="eyebrow">THE TEA LIBRARY</p><h2>${esc(t.title)}</h2>${t.subtitle?`<h3>${esc(t.subtitle)}</h3>`:''}<div class="drawer-image">${img(t.image,t.title,'',t)}</div><p>${esc(t.body)}</p>`;document.getElementById('drawer').classList.add('open');document.getElementById('drawerBackdrop').classList.add('open');document.body.classList.add('drawer-open');}

function openCultivar(name){const c=(data.library.cultivars||[]).find(x=>String(x.name).toLowerCase()===String(name).toLowerCase());if(!c)return;document.getElementById('drawerContent').innerHTML=`<p class="eyebrow">CULTIVAR GALLERY</p><h2>${esc(c.name)}</h2><h3>${esc(c.region||'Japan')}</h3><div class="drawer-image">${img(c.image,c.name,'',c)}</div><p>${esc(c.profile||'')}</p><p><span class="cultivar-pill">${esc(c.tag1||'')}</span> <span class="cultivar-pill">${esc(c.tag2||'')}</span></p>`;document.getElementById('drawer').classList.add('open');document.getElementById('drawerBackdrop').classList.add('open');document.body.classList.add('drawer-open');}
window.closeLibrary=()=>{document.getElementById('drawer').classList.remove('open');document.getElementById('drawerBackdrop').classList.remove('open');document.body.classList.remove('drawer-open');};
window.SHIZUKU_APPLY_DATA=(next)=>{data=clone(next);ensureDefaults();render()};
window.addEventListener('message',e=>{if(e.data?.type==='SHIZUKU_PREVIEW'){data=clone(e.data.data);ensureDefaults();render()}if(e.data?.type==='SHIZUKU_NAVIGATE')document.getElementById(e.data.target)?.scrollIntoView({behavior:'smooth'});if(e.data?.type==='SHIZUKU_OPEN_LIBRARY')openTopic(e.data.topic);});
render();
})();
